In [125]:
import pandas as pd
import numpy as np 
import sklearn

In [126]:
df = pd.read_csv('medical_cost_prediction_dataset.csv')

In [127]:
df.head()

,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost,annual_medical_cost
0,69,Male,29.4,No,1,0,0,0,Medium,14825,4.4,8,1,0,4,Private,80,Semi-Urban,10885,2645.50
1,32,Female,22.9,No,1,0,0,0,Medium,3620,6.0,7,4,3,0,Government,64,Semi-Urban,18722,10959.70
2,89,Male,25.7,No,0,0,0,0,High,10578,4.5,7,2,0,3,NaN,0,Urban,4196,8409.80
3,78,Male,31.9,Yes,0,1,0,0,Low,6226,8.6,9,6,1,7,Government,70,Urban,11128,7996.62
4,38,Male,27.7,No,0,0,0,0,High,6253,5.7,3,6,0,6,Private,77,Urban,15110,3202.52

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      5000 non-null   int64
 1   gender                   5000 non-null   object
 2   bmi                      5000 non-null   float64
 3   smoker                   5000 non-null   object
 4   diabetes                 5000 non-null   int64
 5   hypertension             5000 non-null   int64
 6   heart_disease            5000 non-null   int64
 7   asthma                   5000 non-null   int64
 8   physical_activity_level  5000 non-null   object
 9   daily_steps              5000 non-null   int64
 10  sleep_hours              5000 non-null   float64
 11  stress_level             5000 non-null   int64
 12  doctor_visits_per_year   5000 non-null   int64
 13  hospital_admissions      5000 non-null   int64
 14  medication_count         5000 non-null   int64
 15  insurance_type           3952 non-null   object
 16  insurance_coverage_pct   5000 non-null   int64
 17  city_type                5000 non-null   object
 18  previous_year_cost       5000 non-null   int64
 19  annual_medical_cost      5000 non-null   float64
dtypes: float64(3), int64(12), object(5)
memory usage: 781.4+ KB

In [129]:
df.isnull().sum()

age                           0
gender                        0
bmi                           0
smoker                        0
diabetes                      0
hypertension                  0
heart_disease                 0
asthma                        0
physical_activity_level       0
daily_steps                   0
sleep_hours                   0
stress_level                  0
doctor_visits_per_year        0
hospital_admissions           0
medication_count              0
insurance_type             1048
insurance_coverage_pct        0
city_type                     0
previous_year_cost            0
annual_medical_cost           0
dtype: int64

In [130]:
df[df.duplicated()]

Empty DataFrame
Columns: [age, gender, bmi, smoker, diabetes, hypertension, heart_disease, asthma, physical_activity_level, daily_steps, sleep_hours, stress_level, doctor_visits_per_year, hospital_admissions, medication_count, insurance_type, insurance_coverage_pct, city_type, previous_year_cost, annual_medical_cost]
Index: []

In [131]:
## replacing missing values

In [132]:
for i in df.select_dtypes(include='object'):
    df[i].fillna('unknown',inplace = True)

C:\Users\saich\AppData\Local\Temp\ipykernel_24980\3649921610.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna('unknown',inplace = True)

In [133]:
for i in df.select_dtypes(include = 'number'):
    df[i].fillna(df[i].median(),inplace=True)

C:\Users\saich\AppData\Local\Temp\ipykernel_24980\4104996933.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].median(),inplace=True)

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      5000 non-null   int64
 1   gender                   5000 non-null   object
 2   bmi                      5000 non-null   float64
 3   smoker                   5000 non-null   object
 4   diabetes                 5000 non-null   int64
 5   hypertension             5000 non-null   int64
 6   heart_disease            5000 non-null   int64
 7   asthma                   5000 non-null   int64
 8   physical_activity_level  5000 non-null   object
 9   daily_steps              5000 non-null   int64
 10  sleep_hours              5000 non-null   float64
 11  stress_level             5000 non-null   int64
 12  doctor_visits_per_year   5000 non-null   int64
 13  hospital_admissions      5000 non-null   int64
 14  medication_count         5000 non-null   int64
 15  insurance_type           5000 non-null   object
 16  insurance_coverage_pct   5000 non-null   int64
 17  city_type                5000 non-null   object
 18  previous_year_cost       5000 non-null   int64
 19  annual_medical_cost      5000 non-null   float64
dtypes: float64(3), int64(12), object(5)
memory usage: 781.4+ KB

In [135]:
df.columns

Index(['age', 'gender', 'bmi', 'smoker', 'diabetes', 'hypertension',
       'heart_disease', 'asthma', 'physical_activity_level', 'daily_steps',
       'sleep_hours', 'stress_level', 'doctor_visits_per_year',
       'hospital_admissions', 'medication_count', 'insurance_type',
       'insurance_coverage_pct', 'city_type', 'previous_year_cost',
       'annual_medical_cost'],
      dtype='object')

In [136]:
for i in df:
    print('*'*10,i,'*'*10)
    print(df[i].unique())
    print()

********** age **********
[69 32 89 78 38 41 20 39 70 19 47 55 81 77 50 75 66 76 59 79 64 68 72 24
 56 35 21 31 26 88 61 25 52 53 67 23 71 80 51 65 57 43 58 46 62 82 18 28
 22 45 29 40 54 44 60 30 49 83 74 87 73 36 85 34 86 33 37 84 48 42 63 27]

********** gender **********
['Male' 'Female']

********** bmi **********
[29.4 22.9 25.7 31.9 27.7 23.  22.8 21.7 23.3 29.8 24.9 19.3 34.8 27.6
 19.  23.8 26.6 34.5 20.5 30.9 33.  24.6 20.8 25.  25.8 29.3 31.5 22.3
 16.2 25.9 27.5 27.2 24.4 33.6 27.9 24.1 23.5 25.2 34.2 25.1 23.6 35.8
 28.3 26.4 26.2 14.1 29.7 26.7 28.1 22.4 23.9 31.1 36.4 28.2 19.6 25.4
 22.7 15.  34.  29.5 28.7 26.8 19.1 30.2 20.7 13.3 25.3 29.6 29.2 27.3
 32.  18.4 28.5 29.1 19.8 18.5 31.6 26.1 32.5 32.6 27.1 38.5 24.2 30.8
 34.4 34.3 32.1 17.6 36.2 21.1 28.  18.7 31.2 29.9 31.4 27.4 21.  26.
 24.3 27.  35.5 31.8 12.3 33.7 23.2 24.7 22.2 17.3 25.5 30.5 26.5 23.4
 13.2 17.1 21.3 28.4 34.6 21.9 27.8 30.3 22.1 11.8 32.8 33.8 33.2 30.7
 21.6 22.  32.9 22.6 21.4 18.6 18.8 32.7 40.1 19.4 26.9 21.2 32.3 19.7
 26.3 28.6 24.  15.6 28.8 16.5 19.9 24.8 23.1 28.9 33.1 17.2 19.2 25.6
 17.9 35.4 21.8 19.5 36.5 29.  35.7 13.5 41.5 35.1 14.5 39.5 13.8 20.4
 30.1 20.  15.4 40.6 17.  14.9 24.5 32.2 22.5 32.4 14.  14.7 31.  18.1
 13.4 31.3 21.5 11.5 30.  16.6 14.4 37.2 18.3 17.7 36.3 15.2 34.1 36.
 20.1 31.7 36.9 17.8 18.9 17.5 37.  33.5 39.2 37.9 20.3 37.7 35.3 18.2
 30.4 33.9 17.4 20.6 12.4 37.5 20.2 13.6 30.6 33.3 16.3 37.6 39.9 36.7
 16.1 34.9 18.  33.4 23.7 12.9 16.9 15.9 20.9 12.5 12.6 16.8 34.7 37.8
 15.8 35.  40.7 14.2 15.5 35.2 38.2 38.6 43.6 38.8 39.3 35.6 14.6 39.6
  9.9 12.7 15.7 36.6 41.6 16.4 38.3 35.9 11.2 10.8 37.4 40.  14.8 12.1
 38.   7.6 15.3  8.  39.  11.7 40.3 38.1 36.8 10.3 37.3 41.   9.8  6.8
 42.9 11.3 37.1 38.9 41.8 16.  36.1 39.8 16.7 12.  38.7  6.4 14.3 13.7]

********** smoker **********
['No' 'Yes']

********** diabetes **********
[1 0]

********** hypertension **********
[0 1]

********** heart_disease **********
[0 1]

********** asthma **********
[0 1]

********** physical_activity_level **********
['Medium' 'High' 'Low']

********** daily_steps **********
[14825  3620 10578 ...  1517  8379  2000]

********** sleep_hours **********
[4.4 6.  4.5 8.6 5.7 7.7 4.6 7.4 8.2 5.  6.1 7.1 8.  6.7 8.4 8.3 6.9 9.
 6.4 7.9 4.7 8.9 5.8 5.1 5.4 4.3 6.5 5.9 5.5 6.8 6.3 5.2 7.8 8.8 6.2 7.
 4.1 7.6 8.7 7.2 8.1 8.5 7.5 4.  4.2 4.9 5.3 5.6 6.6 4.8 7.3]

********** stress_level **********
[ 8  7  9  3 10  6  4  1  5  2]

********** doctor_visits_per_year **********
[ 1  4  2  6  5  3  8  0  7 12  9 11 13 10 14]

********** hospital_admissions **********
[0 3 1 2 4 5 6]

********** medication_count **********
[4 0 3 7 6 2 1 5]

********** insurance_type **********
['Private' 'Government' 'unknown']

********** insurance_coverage_pct **********
[80 64  0 70 77 89 71 66 54 50 82 63 52 51 72 83 53 78 62 69 87 93 61 67
 73 79 68 59 88 56 90 65 55 58 57 76 92 81 74 75 84 94 60 85 91 86]

********** city_type **********
['Semi-Urban' 'Urban' 'Rural']

********** previous_year_cost **********
[10885 18722  4196 ... 16543 11310 17078]

********** annual_medical_cost **********
[ 2645.5  10959.7   8409.8  ...  3354.62  1401.72  6548.04]

## Step 1- Splitting inputs (X) and output (y)

In [137]:
# indentifying our target variable and splitting Inputs(features) X and Output y

In [138]:
df.head(2)

,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost,annual_medical_cost
0,69,Male,29.4,No,1,0,0,0,Medium,14825,4.4,8,1,0,4,Private,80,Semi-Urban,10885,2645.5
1,32,Female,22.9,No,1,0,0,0,Medium,3620,6.0,7,4,3,0,Government,64,Semi-Urban,18722,10959.7

In [139]:
X = df.drop('annual_medical_cost',axis=1)

In [140]:
y = df[['annual_medical_cost']]

In [141]:
y

      annual_medical_cost
0                 2645.50
1                10959.70
2                 8409.80
3                 7996.62
4                 3202.52
...                   ...
4995              3513.76
4996              9816.10
4997              3354.62
4998              1401.72
4999              6548.04

[5000 rows x 1 columns]

## Step 2- Splitting the data into TEST(X_train, y_train) and TRAIN(X_test)

In [142]:
# As we cannot pass the actual/whole data directly to the model we are Splitting TEST(X_train, y_train) and TRAIN(X_test) data with 80-20 ratio

In [143]:
# inorder to break the data into train and test we use this formula 
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state = 42)

In [144]:
X_train

,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost
4227,73,Male,27.4,No,0,0,0,0,High,2806,6.6,9,1,1,6,Private,79,Urban,11798
4676,53,Female,22.5,No,0,0,1,0,Low,6800,4.5,9,7,0,4,Private,78,Semi-Urban,5956
800,52,Female,24.9,No,0,1,0,0,High,7567,8.0,5,7,2,6,Private,85,Semi-Urban,14943
3671,49,Male,24.3,No,1,0,1,0,Medium,11050,8.1,5,4,0,5,Government,64,Semi-Urban,6355
4193,40,Male,38.0,No,0,0,0,0,Medium,3463,6.9,7,3,1,2,Private,80,Urban,19822
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4426,60,Male,29.0,No,0,0,0,0,Medium,1898,8.9,5,3,1,2,unknown,0,Semi-Urban,6929
466,33,Female,25.6,No,0,0,0,0,High,12035,8.4,5,3,1,7,Private,85,Urban,19576
3092,64,Female,24.4,Yes,0,1,1,0,Medium,10186,6.5,3,7,1,0,Government,76,Urban,9218
3772,21,Female,31.3,No,0,0,0,0,Low,2878,4.9,2,7,1,2,Government,62,Urban,859
860,74,Male,20.0,No,0,0,1,0,Low,2959,8.6,2,6,1,1,unknown,0,Semi-Urban,19631

In [145]:
X_test

,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost
1501,36,Male,28.4,No,0,0,0,0,Low,3701,5.5,2,5,0,0,Government,65,Urban,7029
2586,39,Male,14.1,No,0,0,0,0,High,3051,4.2,4,4,3,1,unknown,0,Semi-Urban,7744
2653,86,Female,24.7,No,0,0,0,0,Medium,2059,6.8,1,2,1,3,Private,72,Rural,7592
1055,39,Female,32.6,No,0,0,0,0,Low,8737,6.7,9,5,2,0,Private,93,Semi-Urban,7020
705,40,Female,30.8,Yes,0,0,0,0,Low,10271,6.6,3,4,2,1,Government,51,Urban,17125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4711,60,Male,31.6,Yes,1,1,0,0,Low,3368,7.7,1,4,3,0,Government,56,Urban,13923
2313,78,Male,27.5,No,0,0,0,0,Low,5133,5.8,6,2,0,2,Private,92,Urban,19366
3214,26,Male,27.2,No,0,1,0,0,Low,2559,5.8,3,5,0,6,Government,62,Urban,1428
2732,54,Male,34.7,Yes,0,0,0,0,High,5031,7.8,3,3,3,1,Government,79,Urban,16310
1926,31,Male,22.2,No,0,0,0,0,High,4234,8.4,6,1,3,5,Private,74,Semi-Urban,12739

In [146]:
y_train

      annual_medical_cost
4227              3952.49
4676              3590.80
800               4330.49
3671              6377.58
4193              3617.32
...                   ...
4426             13948.70
466               3165.12
3092              5802.58
3772              4718.35
860              22569.30

[4000 rows x 1 columns]

In [147]:
y_test

      annual_medical_cost
1501              2128.24
2586             24726.20
2653              3958.81
1055              1376.48
705              12182.14
...                   ...
4711             14794.96
2313               943.58
3214              4242.47
2732              6428.94
1926              7464.00

[1000 rows x 1 columns]

In [148]:
reset = [X_train,X_test,y_train,y_test]

In [149]:
for i in reset:
    i.reset_index(inplace=True)

In [150]:
X_train

,index,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost
0,4227,73,Male,27.4,No,0,0,0,0,High,2806,6.6,9,1,1,6,Private,79,Urban,11798
1,4676,53,Female,22.5,No,0,0,1,0,Low,6800,4.5,9,7,0,4,Private,78,Semi-Urban,5956
2,800,52,Female,24.9,No,0,1,0,0,High,7567,8.0,5,7,2,6,Private,85,Semi-Urban,14943
3,3671,49,Male,24.3,No,1,0,1,0,Medium,11050,8.1,5,4,0,5,Government,64,Semi-Urban,6355
4,4193,40,Male,38.0,No,0,0,0,0,Medium,3463,6.9,7,3,1,2,Private,80,Urban,19822
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,4426,60,Male,29.0,No,0,0,0,0,Medium,1898,8.9,5,3,1,2,unknown,0,Semi-Urban,6929
3996,466,33,Female,25.6,No,0,0,0,0,High,12035,8.4,5,3,1,7,Private,85,Urban,19576
3997,3092,64,Female,24.4,Yes,0,1,1,0,Medium,10186,6.5,3,7,1,0,Government,76,Urban,9218
3998,3772,21,Female,31.3,No,0,0,0,0,Low,2878,4.9,2,7,1,2,Government,62,Urban,859
3999,860,74,Male,20.0,No,0,0,1,0,Low,2959,8.6,2,6,1,1,unknown,0,Semi-Urban,19631

In [151]:
X_test

,index,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost
0,1501,36,Male,28.4,No,0,0,0,0,Low,3701,5.5,2,5,0,0,Government,65,Urban,7029
1,2586,39,Male,14.1,No,0,0,0,0,High,3051,4.2,4,4,3,1,unknown,0,Semi-Urban,7744
2,2653,86,Female,24.7,No,0,0,0,0,Medium,2059,6.8,1,2,1,3,Private,72,Rural,7592
3,1055,39,Female,32.6,No,0,0,0,0,Low,8737,6.7,9,5,2,0,Private,93,Semi-Urban,7020
4,705,40,Female,30.8,Yes,0,0,0,0,Low,10271,6.6,3,4,2,1,Government,51,Urban,17125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,4711,60,Male,31.6,Yes,1,1,0,0,Low,3368,7.7,1,4,3,0,Government,56,Urban,13923
996,2313,78,Male,27.5,No,0,0,0,0,Low,5133,5.8,6,2,0,2,Private,92,Urban,19366
997,3214,26,Male,27.2,No,0,1,0,0,Low,2559,5.8,3,5,0,6,Government,62,Urban,1428
998,2732,54,Male,34.7,Yes,0,0,0,0,High,5031,7.8,3,3,3,1,Government,79,Urban,16310
999,1926,31,Male,22.2,No,0,0,0,0,High,4234,8.4,6,1,3,5,Private,74,Semi-Urban,12739

In [152]:
y_train

      index  annual_medical_cost
0      4227              3952.49
1      4676              3590.80
2       800              4330.49
3      3671              6377.58
4      4193              3617.32
...     ...                  ...
3995   4426             13948.70
3996    466              3165.12
3997   3092              5802.58
3998   3772              4718.35
3999    860             22569.30

[4000 rows x 2 columns]

In [153]:
y_test

     index  annual_medical_cost
0     1501              2128.24
1     2586             24726.20
2     2653              3958.81
3     1055              1376.48
4      705             12182.14
..     ...                  ...
995   4711             14794.96
996   2313               943.58
997   3214              4242.47
998   2732              6428.94
999   1926              7464.00

[1000 rows x 2 columns]

In [154]:
rest_b = [y_train,y_test]
for i in rest_b:
    i.pop('index')

In [155]:
y_train

      annual_medical_cost
0                 3952.49
1                 3590.80
2                 4330.49
3                 6377.58
4                 3617.32
...                   ...
3995             13948.70
3996              3165.12
3997              5802.58
3998              4718.35
3999             22569.30

[4000 rows x 1 columns]

In [156]:
y_test

     annual_medical_cost
0                2128.24
1               24726.20
2                3958.81
3                1376.48
4               12182.14
..                   ...
995             14794.96
996               943.58
997              4242.47
998              6428.94
999              7464.00

[1000 rows x 1 columns]

- AS Algorithms will only understand numerical values we cannot pass the data yet.
- We have to perform feature engineering on the features of the data 
- but before applying feature engineering, we have to understand what are the data types of inputs
- and split them into following groups
- *numbers*
- *categorical*
- *no transformation features*

In [157]:
cat_df = X_train.select_dtypes(include= 'object')
cat_df

      gender smoker physical_activity_level insurance_type   city_type
0       Male     No                    High        Private       Urban
1     Female     No                     Low        Private  Semi-Urban
2     Female     No                    High        Private  Semi-Urban
3       Male     No                  Medium     Government  Semi-Urban
4       Male     No                  Medium        Private       Urban
...      ...    ...                     ...            ...         ...
3995    Male     No                  Medium        unknown  Semi-Urban
3996  Female     No                    High        Private       Urban
3997  Female    Yes                  Medium     Government       Urban
3998  Female     No                     Low     Government       Urban
3999    Male     No                     Low        unknown  Semi-Urban

[4000 rows x 5 columns]

In [158]:
df.columns

Index(['age', 'gender', 'bmi', 'smoker', 'diabetes', 'hypertension',
       'heart_disease', 'asthma', 'physical_activity_level', 'daily_steps',
       'sleep_hours', 'stress_level', 'doctor_visits_per_year',
       'hospital_admissions', 'medication_count', 'insurance_type',
       'insurance_coverage_pct', 'city_type', 'previous_year_cost',
       'annual_medical_cost'],
      dtype='object')

In [159]:
df.head(2)

,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost,annual_medical_cost
0,69,Male,29.4,No,1,0,0,0,Medium,14825,4.4,8,1,0,4,Private,80,Semi-Urban,10885,2645.5
1,32,Female,22.9,No,1,0,0,0,Medium,3620,6.0,7,4,3,0,Government,64,Semi-Urban,18722,10959.7

In [160]:
num_df = X_train[['age','bmi','daily_steps','sleep_hours','stress_level','doctor_visits_per_year','hospital_admissions','medication_count','insurance_coverage_pct','previous_year_cost']]
num_df

,age,bmi,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_coverage_pct,previous_year_cost
0,73,27.4,2806,6.6,9,1,1,6,79,11798
1,53,22.5,6800,4.5,9,7,0,4,78,5956
2,52,24.9,7567,8.0,5,7,2,6,85,14943
3,49,24.3,11050,8.1,5,4,0,5,64,6355
4,40,38.0,3463,6.9,7,3,1,2,80,19822
...,...,...,...,...,...,...,...,...,...,...
3995,60,29.0,1898,8.9,5,3,1,2,0,6929
3996,33,25.6,12035,8.4,5,3,1,7,85,19576
3997,64,24.4,10186,6.5,3,7,1,0,76,9218
3998,21,31.3,2878,4.9,2,7,1,2,62,859
3999,74,20.0,2959,8.6,2,6,1,1,0,19631

In [161]:
no_trans = X_train[['diabetes','hypertension','heart_disease','asthma']]
no_trans

      diabetes  hypertension  heart_disease  asthma
0            0             0              0       0
1            0             0              1       0
2            0             1              0       0
3            1             0              1       0
4            0             0              0       0
...        ...           ...            ...     ...
3995         0             0              0       0
3996         0             0              0       0
3997         0             1              1       0
3998         0             0              0       0
3999         0             0              1       0

[4000 rows x 4 columns]

In [162]:
# noww transforming our cat_df and num_df using feature engineering

## Step 3 - Feature Engineering on inputs

#### Performing One Hot Encoding(O.H.E) on categorical features(cat_df) of X_train

In [163]:
from sklearn.preprocessing import OneHotEncoder
OHE = OneHotEncoder(sparse_output=False).set_output(transform='pandas')
cat_df_trans = OHE.fit_transform(cat_df)

In [164]:
cat_df_trans

,gender_Female,gender_Male,smoker_No,smoker_Yes,physical_activity_level_High,physical_activity_level_Low,physical_activity_level_Medium,insurance_type_Government,insurance_type_Private,insurance_type_unknown,city_type_Rural,city_type_Semi-Urban,city_type_Urban
0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
3996,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3997,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
3998,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3999,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

#### Performing MinMaxScaler on numerical features(num_df) of X_train (Normalization)

In [165]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler().set_output(transform='pandas')
num_df_trans = scaler.fit_transform(num_df)

In [166]:
num_df_trans

,age,bmi,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_coverage_pct,previous_year_cost
0,0.774648,0.564516,0.128760,0.52,0.888889,0.071429,0.166667,0.857143,0.840426,0.579503
1,0.492958,0.432796,0.414148,0.10,0.888889,0.500000,0.000000,0.571429,0.829787,0.279852
2,0.478873,0.497312,0.468953,0.80,0.444444,0.500000,0.333333,0.857143,0.904255,0.740819
3,0.436620,0.481183,0.717828,0.82,0.444444,0.285714,0.000000,0.714286,0.680851,0.300318
4,0.309859,0.849462,0.175706,0.58,0.666667,0.214286,0.166667,0.285714,0.851064,0.991075
...,...,...,...,...,...,...,...,...,...,...
3995,0.591549,0.607527,0.063880,0.98,0.444444,0.214286,0.166667,0.285714,0.000000,0.329760
3996,0.211268,0.516129,0.788210,0.88,0.444444,0.214286,0.166667,1.000000,0.904255,0.978457
3997,0.647887,0.483871,0.656091,0.50,0.222222,0.500000,0.166667,0.000000,0.808511,0.447169
3998,0.042254,0.669355,0.133905,0.18,0.111111,0.500000,0.166667,0.285714,0.659574,0.018414
3999,0.788732,0.365591,0.139693,0.92,0.111111,0.428571,0.166667,0.142857,0.000000,0.981278

In [167]:
X_train_trans = pd.concat([cat_df_trans,num_df_trans,no_trans],axis=1)

In [168]:
X_train_trans

,gender_Female,gender_Male,smoker_No,smoker_Yes,physical_activity_level_High,physical_activity_level_Low,physical_activity_level_Medium,insurance_type_Government,insurance_type_Private,insurance_type_unknown,...,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_coverage_pct,previous_year_cost,diabetes,hypertension,heart_disease,asthma
0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.888889,0.071429,0.166667,0.857143,0.840426,0.579503,0,0,0,0
1,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.888889,0.500000,0.000000,0.571429,0.829787,0.279852,0,0,1,0
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.444444,0.500000,0.333333,0.857143,0.904255,0.740819,0,1,0,0
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.444444,0.285714,0.000000,0.714286,0.680851,0.300318,1,0,1,0
4,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.666667,0.214286,0.166667,0.285714,0.851064,0.991075,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.444444,0.214286,0.166667,0.285714,0.000000,0.329760,0,0,0,0
3996,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.444444,0.214286,0.166667,1.000000,0.904255,0.978457,0,0,0,0
3997,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.222222,0.500000,0.166667,0.000000,0.808511,0.447169,0,1,1,0
3998,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.111111,0.500000,0.166667,0.285714,0.659574,0.018414,0,0,0,0
3999,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.111111,0.428571,0.166667,0.142857,0.000000,0.981278,0,0,1,0

## Step 4- Model training using Algorithmn X_test_trans and y_train

In [169]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor()
model.fit(X_train_trans,y_train)

KNeighborsRegressor()

## Step 5 - Feature engineering on Test data

#### inorder to pass our test data to model
- first we have to transform the data by applying feature engineering

In [170]:
cat_df = X_test.select_dtypes(include='object')
cat_df

     gender smoker physical_activity_level insurance_type   city_type
0      Male     No                     Low     Government       Urban
1      Male     No                    High        unknown  Semi-Urban
2    Female     No                  Medium        Private       Rural
3    Female     No                     Low        Private  Semi-Urban
4    Female    Yes                     Low     Government       Urban
..      ...    ...                     ...            ...         ...
995    Male    Yes                     Low     Government       Urban
996    Male     No                     Low        Private       Urban
997    Male     No                     Low     Government       Urban
998    Male    Yes                    High     Government       Urban
999    Male     No                    High        Private  Semi-Urban

[1000 rows x 5 columns]

In [171]:
num_df = X_test[['age','bmi','daily_steps','sleep_hours','stress_level','doctor_visits_per_year','hospital_admissions','medication_count','insurance_coverage_pct','previous_year_cost']]
num_df

,age,bmi,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_coverage_pct,previous_year_cost
0,36,28.4,3701,5.5,2,5,0,0,65,7029
1,39,14.1,3051,4.2,4,4,3,1,0,7744
2,86,24.7,2059,6.8,1,2,1,3,72,7592
3,39,32.6,8737,6.7,9,5,2,0,93,7020
4,40,30.8,10271,6.6,3,4,2,1,51,17125
...,...,...,...,...,...,...,...,...,...,...
995,60,31.6,3368,7.7,1,4,3,0,56,13923
996,78,27.5,5133,5.8,6,2,0,2,92,19366
997,26,27.2,2559,5.8,3,5,0,6,62,1428
998,54,34.7,5031,7.8,3,3,3,1,79,16310
999,31,22.2,4234,8.4,6,1,3,5,74,12739

In [172]:
no_trans = X_test[['diabetes','hypertension','heart_disease','asthma']]
no_trans

     diabetes  hypertension  heart_disease  asthma
0           0             0              0       0
1           0             0              0       0
2           0             0              0       0
3           0             0              0       0
4           0             0              0       0
..        ...           ...            ...     ...
995         1             1              0       0
996         0             0              0       0
997         0             1              0       0
998         0             0              0       0
999         0             0              0       0

[1000 rows x 4 columns]

In [173]:
cat_df_trans = OHE.transform(cat_df)

In [174]:
num_df_trans = scaler.transform(num_df)

In [175]:
cat_df_trans

,gender_Female,gender_Male,smoker_No,smoker_Yes,physical_activity_level_High,physical_activity_level_Low,physical_activity_level_Medium,insurance_type_Government,insurance_type_Private,insurance_type_unknown,city_type_Rural,city_type_Semi-Urban,city_type_Urban
0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
3,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
996,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
997,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
998,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
999,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [176]:
num_df_trans

,age,bmi,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_coverage_pct,previous_year_cost
0,0.253521,0.591398,0.192712,0.30,0.111111,0.357143,0.000000,0.000000,0.691489,0.334889
1,0.295775,0.206989,0.146267,0.04,0.333333,0.285714,0.500000,0.142857,0.000000,0.371563
2,0.957746,0.491935,0.075384,0.56,0.000000,0.142857,0.166667,0.428571,0.765957,0.363767
3,0.295775,0.704301,0.552554,0.54,0.888889,0.357143,0.333333,0.000000,0.989362,0.334428
4,0.309859,0.655914,0.662165,0.52,0.222222,0.285714,0.333333,0.142857,0.542553,0.852739
...,...,...,...,...,...,...,...,...,...,...
995,0.591549,0.677419,0.168917,0.74,0.000000,0.285714,0.500000,0.000000,0.595745,0.688500
996,0.845070,0.567204,0.295034,0.36,0.555556,0.142857,0.000000,0.285714,0.978723,0.967686
997,0.112676,0.559140,0.111111,0.36,0.222222,0.357143,0.000000,0.857143,0.659574,0.047600
998,0.507042,0.760753,0.287746,0.76,0.222222,0.214286,0.500000,0.142857,0.840426,0.810936
999,0.183099,0.424731,0.230797,0.88,0.555556,0.071429,0.500000,0.714286,0.787234,0.627770

In [177]:
X_test_trans = pd.concat([cat_df_trans,num_df_trans,no_trans],axis=1)

In [178]:
X_test_trans

,gender_Female,gender_Male,smoker_No,smoker_Yes,physical_activity_level_High,physical_activity_level_Low,physical_activity_level_Medium,insurance_type_Government,insurance_type_Private,insurance_type_unknown,...,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_coverage_pct,previous_year_cost,diabetes,hypertension,heart_disease,asthma
0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.111111,0.357143,0.000000,0.000000,0.691489,0.334889,0,0,0,0
1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.333333,0.285714,0.500000,0.142857,0.000000,0.371563,0,0,0,0
2,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.000000,0.142857,0.166667,0.428571,0.765957,0.363767,0,0,0,0
3,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.888889,0.357143,0.333333,0.000000,0.989362,0.334428,0,0,0,0
4,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.222222,0.285714,0.333333,0.142857,0.542553,0.852739,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.000000,0.285714,0.500000,0.000000,0.595745,0.688500,1,1,0,0
996,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.555556,0.142857,0.000000,0.285714,0.978723,0.967686,0,0,0,0
997,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.222222,0.357143,0.000000,0.857143,0.659574,0.047600,0,1,0,0
998,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.222222,0.214286,0.500000,0.142857,0.840426,0.810936,0,0,0,0
999,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.555556,0.071429,0.500000,0.714286,0.787234,0.627770,0,0,0,0

## Step 6 - Prediction on X_test_trans

#### here we are pasing our test inputs (X_test_trans) to teh model to get our prediction output(y_pred)

In [179]:
y_pred = model.predict(X_test_trans)

In [180]:
y_pred

array([[ 6071.972],
       [16875.46 ],
       [ 2696.766],
       [ 3025.984],
       [ 6119.074],
       [ 1698.044],
       [ 3865.454],
       [ 3397.934],
       [ 4053.468],
       [19341.98 ],
       [19974.86 ],
       [ 2684.838],
       [ 7474.072],
       [ 2980.828],
       [ 7584.162],
       [ 6160.02 ],
       [ 6065.822],
       [ 5638.25 ],
       [ 5566.25 ],
       [ 7516.572],
       [ 9313.66 ],
       [ 6962.558],
       [13191.82 ],
       [ 4649.676],
       [ 9357.982],
       [ 6863.836],
       [ 3897.912],
       [ 4020.746],
       [ 3874.108],
       [ 5536.672],
       [20656.34 ],
       [ 6678.842],
       [ 8229.272],
       [ 2998.676],
       [ 4181.138],
       [12499.42 ],
       [ 3623.35 ],
       [ 2777.554],
       [ 6508.482],
       [19806.04 ],
       [ 5508.638],
       [16490.08 ],
       [20402.34 ],
       [ 7646.216],
       [ 4696.24 ],
       [ 7522.352],
       [ 3129.228],
       [ 4459.986],
       [17088.08 ],
       [ 7150.54 ],
       [ 6379.134],
       [ 4823.618],
       [ 7480.426],
       [17710.8  ],
       [ 3207.582],
       [ 5755.858],
       [15509.64 ],
       [19337.72 ],
       [ 3993.104],
       [ 7006.592],
       [11782.476],
       [ 4694.762],
       [ 7735.21 ],
       [18953.28 ],
       [ 6081.82 ],
       [ 6073.922],
       [21013.98 ],
       [ 3707.924],
       [ 6218.434],
       [20498.92 ],
       [16868.06 ],
       [ 9678.356],
       [ 5470.54 ],
       [14579.24 ],
       [ 2652.572],
       [ 3885.052],
       [ 3336.334],
       [ 4262.01 ],
       [16704.52 ],
       [ 5737.05 ],
       [ 6438.816],
       [18270.28 ],
       [ 7754.142],
       [ 6964.988],
       [ 7480.128],
       [20815.5  ],
       [18297.4  ],
       [ 3426.   ],
       [22018.38 ],
       [ 5478.998],
       [ 4018.91 ],
       [ 4752.674],
       [ 3968.786],
       [16349.08 ],
       [ 3768.558],
       [13506.52 ],
       [24220.56 ],
       [ 3427.378],
       [16120.2  ],
       [18247.5  ],
       [ 6440.754],
       [ 6704.48 ],
       [ 3625.712],
       [ 6013.388],
       [ 4872.744],
       [ 9301.752],
       [ 3794.578],
       [ 5153.192],
       [18419.58 ],
       [ 8940.632],
       [ 4195.748],
       [15508.48 ],
       [18206.18 ],
       [18808.14 ],
       [ 2619.938],
       [ 4863.004],
       [17992.58 ],
       [ 4457.232],
       [ 6065.934],
       [ 4372.238],
       [ 5505.86 ],
       [12060.04 ],
       [ 4768.922],
       [ 4160.73 ],
       [ 6347.884],
       [ 2628.29 ],
       [ 2897.818],
       [ 2099.186],
       [ 3173.74 ],
       [15606.64 ],
       [ 6261.994],
       [12413.922],
       [ 6499.786],
       [12136.46 ],
       [ 3692.328],
       [ 5071.996],
       [ 3551.206],
       [ 4442.554],
       [ 6873.362],
       [ 2885.836],
       [ 5754.026],
       [13089.14 ],
       [18025.76 ],
       [ 7217.31 ],
       [ 3360.138],
       [ 6608.474],
       [ 4785.122],
       [ 4184.678],
       [ 4538.306],
       [ 1546.768],
       [ 3253.786],
       [ 5447.248],
       [ 2590.73 ],
       [ 2216.832],
       [ 6541.708],
       [ 7406.824],
       [14211.7  ],
       [ 6693.446],
       [ 3903.064],
       [ 4132.962],
       [ 2156.246],
       [ 7378.414],
       [ 5496.214],
       [ 3590.608],
       [ 7791.026],
       [ 6558.708],
       [ 3230.688],
       [ 2894.864],
       [ 9188.006],
       [13232.4  ],
       [17613.24 ],
       [ 6254.17 ],
       [ 1738.028],
       [ 9176.928],
       [ 4494.65 ],
       [ 6480.13 ],
       [ 3892.498],
       [ 5753.572],
       [ 3728.708],
       [ 6112.636],
       [ 6970.73 ],
       [ 2877.186],
       [ 5363.704],
       [ 5244.886],
       [19982.38 ],
       [ 1265.31 ],
       [ 9207.466],
       [ 4704.224],
       [ 4231.218],
       [ 7347.642],
       [ 3748.836],
       [ 5512.444],
       [ 5231.404],
       [15849.78 ],
       [ 2958.554],
       [ 4793.516],
       [ 6576.9  ],
       [ 1730.366],
       [ 2072.118],
       [ 3108.382],
       [ 6369.73 ],
       [23662.58 ],
       [ 3916.894],
       [ 3203.428],
       [ 3825.02 ],
       [19621.08 ],
       [ 2124.33 ],
       [14333.94 ],
       [ 2385.668],
       [ 4507.602],
       [ 7677.752],
       [ 6982.962],
       [ 5566.068],
       [ 6707.478],
       [ 5409.03 ],
       [ 3664.784],
       [ 7977.854],
       [ 4428.654],
       [ 2027.088],
       [14872.56 ],
       [ 3125.632],
       [ 3101.092],
       [ 5630.078],
       [16347.94 ],
       [ 1955.992],
       [ 3839.944],
       [ 3273.53 ],
       [ 2794.654],
       [ 8247.982],
       [ 7512.862],
       [23458.28 ],
       [ 2750.91 ],
       [ 1456.444],
       [ 3709.394],
       [ 2717.654],
       [ 3563.2  ],
       [ 3115.53 ],
       [ 3158.566],
       [13762.82 ],
       [ 5476.424],
       [ 8049.026],
       [ 3693.48 ],
       [ 3156.786],
       [ 2406.38 ],
       [ 3470.674],
       [ 4228.79 ],
       [ 1885.334],
       [ 3577.31 ],
       [ 2473.274],
       [ 3021.28 ],
       [ 3049.128],
       [ 5861.68 ],
       [ 5682.6  ],
       [19644.02 ],
       [ 3319.062],
       [ 6093.232],
       [ 3060.192],
       [22656.14 ],
       [ 1468.596],
       [ 7482.898],
       [ 1905.51 ],
       [ 2448.69 ],
       [ 7703.672],
       [ 2953.818],
       [15989.28 ],
       [ 4240.91 ],
       [ 3102.924],
       [ 6064.584],
       [ 3314.1  ],
       [ 6465.938],
       [14552.18 ],
       [ 3316.034],
       [ 4669.496],
       [18586.76 ],
       [ 3009.846],
       [16975.76 ],
       [ 4083.666],
       [ 4643.626],
       [ 4609.95 ],
       [ 5417.052],
       [ 6846.098],
       [ 6611.314],
       [ 4455.548],
       [20269.08 ],
       [ 3702.33 ],
       [ 6312.452],
       [ 3101.63 ],
       [17994.74 ],
       [ 4160.074],
       [ 6327.914],
       [ 7002.914],
       [ 3006.552],
       [ 5301.306],
       [18900.98 ],
       [ 1746.794],
       [ 3351.766],
       [ 4989.184],
       [16667.68 ],
       [ 3611.446],
       [15924.48 ],
       [ 6912.904],
       [ 3351.718],
       [19353.52 ],
       [21824.7  ],
       [ 3901.068],
       [ 3705.752],
       [ 6305.036],
       [ 3503.544],
       [ 5926.078],
       [ 7689.346],
       [ 5414.674],
       [ 3174.304],
       [ 2728.046],
       [ 2916.876],
       [ 9513.912],
       [ 4393.564],
       [ 3030.142],
       [19387.   ],
       [17935.66 ],
       [ 3310.454],
       [17042.02 ],
       [ 6535.336],
       [19541.42 ],
       [ 5164.33 ],
       [ 7833.996],
       [ 5320.212],
       [14624.66 ],
       [ 2788.582],
       [ 3530.666],
       [ 2185.016],
       [ 2705.074],
       [ 3176.082],
       [ 6661.178],
       [ 2556.592],
       [ 2504.448],
       [20081.44 ],
       [ 2883.274],
       [ 7044.88 ],
       [ 3389.176],
       [ 5822.254],
       [ 4982.29 ],
       [18426.78 ],
       [ 6761.13 ],
       [14175.44 ],
       [ 1663.088],
       [ 4121.498],
       [ 5933.68 ],
       [ 4168.738],
       [ 2489.56 ],
       [ 2770.764],
       [ 7022.096],
       [ 6544.16 ],
       [ 2448.67 ],
       [ 2220.108],
       [ 8748.022],
       [ 6795.552],
       [ 6314.626],
       [ 2870.168],
       [ 4643.242],
       [ 4802.324],
       [17498.34 ],
       [ 4949.126],
       [ 4309.248],
       [ 7471.09 ],
       [17651.46 ],
       [ 3858.524],
       [ 7222.72 ],
       [ 3428.418],
       [ 4020.906],
       [15171.6  ],
       [ 2548.218],
       [ 3262.998],
       [16546.56 ],
       [15819.56 ],
       [ 3288.66 ],
       [15139.38 ],
       [18543.58 ],
       [ 5252.718],
       [ 3540.044],
       [ 2330.21 ],
       [ 6618.342],
       [ 9441.436],
       [ 1803.226],
       [ 6832.648],
       [ 5671.368],
       [ 6421.256],
       [ 6137.818],
       [ 2797.148],
       [ 3302.602],
       [ 3446.55 ],
       [ 8029.49 ],
       [ 3775.62 ],
       [ 7074.74 ],
       [ 6553.162],
       [ 5908.142],
       [ 3677.616],
       [ 3629.154],
       [ 6542.468],
       [ 3074.058],
       [ 7036.002],
       [ 2035.238],
       [ 2892.774],
       [ 5388.572],
       [20531.   ],
       [ 2402.642],
       [18293.12 ],
       [16377.4  ],
       [ 6053.814],
       [ 4348.974],
       [ 4213.848],
       [10747.008],
       [18436.76 ],
       [ 7488.854],
       [ 6449.506],
       [ 6999.324],
       [ 3503.024],
       [ 5974.86 ],
       [ 6688.076],
       [ 7248.04 ],
       [ 4014.612],
       [ 5753.838],
       [ 3521.98 ],
       [18072.52 ],
       [ 6783.494],
       [ 2617.196],
       [ 2872.12 ],
       [24424.22 ],
       [ 8144.026],
       [14829.7  ],
       [ 3586.784],
       [ 8439.53 ],
       [ 3788.814],
       [22498.66 ],
       [ 7019.272],
       [18822.9  ],
       [ 3864.3  ],
       [ 5861.68 ],
       [ 3927.898],
       [14447.66 ],
       [ 3165.154],
       [ 2117.402],
       [18206.18 ],
       [ 2814.184],
       [ 4067.752],
       [ 6834.578],
       [ 8098.526],
       [ 3966.466],
       [ 4520.984],
       [20985.42 ],
       [ 2934.282],
       [13682.9  ],
       [18963.8  ],
       [ 6054.602],
       [ 5136.716],
       [ 2660.514],
       [ 5523.64 ],
       [ 4045.524],
       [ 2657.474],
       [ 6485.966],
       [ 3203.958],
       [ 3214.402],
       [18499.74 ],
       [ 2437.094],
       [ 3797.056],
       [ 6551.028],
       [21313.82 ],
       [ 7806.768],
       [ 8670.744],
       [ 6709.62 ],
       [ 4520.682],
       [18987.28 ],
       [14274.98 ],
       [14920.54 ],
       [ 3281.298],
       [ 4106.46 ],
       [14100.32 ],
       [ 3350.618],
       [ 4916.432],
       [ 6232.89 ],
       [ 2815.752],
       [15937.44 ],
       [13788.36 ],
       [ 6696.272],
       [ 3741.67 ],
       [ 3896.996],
       [ 8555.018],
       [ 2652.924],
       [ 3647.022],
       [14933.72 ],
       [ 3714.912],
       [11228.4  ],
       [ 2885.544],
       [ 7773.018],
       [ 8117.716],
       [ 5456.074],
       [ 2888.002],
       [ 5406.906],
       [ 3583.99 ],
       [ 3076.682],
       [ 5617.21 ],
       [ 3922.966],
       [ 7296.288],
       [17485.62 ],
       [ 5706.614],
       [ 2422.688],
       [ 3066.7  ],
       [ 2790.568],
       [20980.44 ],
       [ 5414.142],
       [ 2903.826],
       [ 3428.08 ],
       [ 5685.738],
       [ 9645.018],
       [ 2421.334],
       [ 3319.948],
       [ 3248.604],
       [ 2607.994],
       [ 3029.904],
       [ 5856.974],
       [ 7151.198],
       [ 3473.294],
       [ 3168.382],
       [ 8832.754],
       [ 4007.516],
       [ 6564.046],
       [ 4062.72 ],
       [ 5907.79 ],
       [16204.5  ],
       [17554.34 ],
       [24858.84 ],
       [ 5563.212],
       [ 5987.64 ],
       [ 2950.744],
       [ 6297.094],
       [ 2158.202],
       [14566.42 ],
       [ 6108.628],
       [ 3041.85 ],
       [16473.86 ],
       [ 5096.122],
       [ 4337.766],
       [ 2360.526],
       [ 6702.184],
       [ 2671.782],
       [ 5653.898],
       [ 1830.484],
       [20598.38 ],
       [ 3759.864],
       [ 4707.156],
       [17491.26 ],
       [12403.28 ],
       [ 3666.008],
       [ 1751.968],
       [ 7526.242],
       [ 6792.96 ],
       [ 4867.356],
       [ 4046.05 ],
       [14100.32 ],
       [18206.18 ],
       [ 3372.604],
       [ 4472.49 ],
       [ 3503.024],
       [ 4701.876],
       [ 7036.66 ],
       [18151.36 ],
       [ 3005.664],
       [ 3233.456],
       [ 3566.15 ],
       [ 6113.996],
       [ 2583.942],
       [ 2851.53 ],
       [ 4098.598],
       [ 2569.852],
       [ 5097.892],
       [ 5725.036],
       [ 8038.214],
       [ 9269.748],
       [ 4841.346],
       [ 3270.684],
       [ 5889.3  ],
       [ 8682.5  ],
       [15932.72 ],
       [ 2426.242],
       [ 2489.234],
       [16125.2  ],
       [ 2871.696],
       [ 3217.43 ],
       [ 5472.988],
       [ 6746.4  ],
       [ 5340.92 ],
       [16557.72 ],
       [ 4108.42 ],
       [ 5808.56 ],
       [ 2971.744],
       [ 4419.268],
       [ 9315.776],
       [16232.76 ],
       [ 1637.312],
       [10292.96 ],
       [ 6530.056],
       [ 2483.348],
       [ 4854.748],
       [ 6860.316],
       [ 5308.674],
       [ 4982.29 ],
       [ 8227.086],
       [ 3780.354],
       [ 7967.944],
       [ 5591.846],
       [ 6106.356],
       [16791.1  ],
       [ 6840.972],
       [ 4262.174],
       [ 2461.224],
       [ 1385.778],
       [ 5667.884],
       [ 2607.414],
       [ 4398.748],
       [ 5121.584],
       [ 8008.25 ],
       [ 6280.452],
       [ 5583.68 ],
       [16746.32 ],
       [ 6784.542],
       [ 5506.208],
       [ 2997.648],
       [ 4684.682],
       [ 2439.736],
       [11434.28 ],
       [18866.66 ],
       [17968.24 ],
       [ 3707.628],
       [ 4262.452],
       [ 9414.394],
       [18075.42 ],
       [ 4860.082],
       [ 2621.85 ],
       [16120.2  ],
       [ 1813.026],
       [14738.96 ],
       [ 3310.902],
       [ 5567.07 ],
       [ 6946.962],
       [18083.16 ],
       [ 3642.226],
       [ 8017.898],
       [ 2892.97 ],
       [ 8754.286],
       [19028.84 ],
       [ 5301.814],
       [ 4226.892],
       [ 2875.408],
       [ 7957.048],
       [ 1929.836],
       [ 4454.95 ],
       [ 6363.476],
       [14027.64 ],
       [ 7447.244],
       [22646.2  ],
       [ 4262.496],
       [ 4489.278],
       [ 3253.84 ],
       [ 3025.312],
       [ 3290.476],
       [ 3009.638],
       [19997.26 ],
       [ 5957.114],
       [ 8649.316],
       [ 3528.394],
       [ 6604.702],
       [12286.68 ],
       [ 5989.66 ],
       [ 2066.75 ],
       [ 5743.72 ],
       [ 5987.914],
       [ 8114.958],
       [21299.94 ],
       [17356.08 ],
       [ 3723.848],
       [17216.22 ],
       [ 4850.672],
       [ 3882.398],
       [23230.18 ],
       [10674.008],
       [ 2492.788],
       [ 2968.056],
       [16505.98 ],
       [ 3199.01 ],
       [ 5375.7  ],
       [ 2346.136],
       [ 5973.284],
       [ 5208.084],
       [19411.08 ],
       [ 2632.01 ],
       [18092.94 ],
       [ 6157.986],
       [ 1874.966],
       [ 5805.012],
       [ 3534.   ],
       [24024.66 ],
       [ 2573.092],
       [ 2072.048],
       [ 2245.444],
       [ 2562.694],
       [23176.94 ],
       [ 5231.72 ],
       [22985.06 ],
       [ 2070.046],
       [ 5325.686],
       [ 5315.168],
       [ 8894.942],
       [13925.78 ],
       [ 2917.152],
       [18907.   ],
       [ 7774.438],
       [17269.38 ],
       [19285.68 ],
       [ 7725.114],
       [21018.4  ],
       [ 4901.004],
       [ 4188.456],
       [ 1749.842],
       [ 2078.21 ],
       [10022.868],
       [10006.264],
       [ 4403.426],
       [ 3049.412],
       [21400.2  ],
       [ 2405.998],
       [22166.44 ],
       [22399.3  ],
       [ 2627.612],
       [ 3600.426],
       [ 2954.112],
       [ 2331.172],
       [ 3402.406],
       [ 5673.35 ],
       [ 6830.414],
       [ 6527.174],
       [ 7233.084],
       [26363.1  ],
       [ 3460.684],
       [ 3873.066],
       [ 4044.992],
       [ 4340.3  ],
       [19860.88 ],
       [22842.92 ],
       [ 7774.688],
       [ 5292.612],
       [13503.6  ],
       [ 3297.398],
       [ 3826.986],
       [ 2470.182],
       [24763.2  ],
       [ 3359.112],
       [ 4841.696],
       [ 4552.434],
       [ 7700.946],
       [ 2752.802],
       [ 3059.194],
       [ 2679.94 ],
       [ 4485.88 ],
       [ 3400.194],
       [ 6543.066],
       [ 1990.42 ],
       [19439.3  ],
       [28168.28 ],
       [ 5175.506],
       [ 4165.576],
       [ 2699.322],
       [20654.36 ],
       [ 2793.984],
       [15908.62 ],
       [ 6109.942],
       [ 5822.254],
       [19061.02 ],
       [19359.08 ],
       [15007.8  ],
       [ 5068.584],
       [ 1583.19 ],
       [ 7857.31 ],
       [19872.96 ],
       [ 4880.37 ],
       [ 1795.264],
       [ 2143.3  ],
       [ 3364.954],
       [15939.56 ],
       [13380.18 ],
       [ 6369.356],
       [ 3210.212],
       [ 6962.558],
       [ 3808.19 ],
       [15662.9  ],
       [ 3067.774],
       [ 3093.024],
       [ 6407.09 ],
       [17015.16 ],
       [ 3414.206],
       [ 3907.08 ],
       [ 6545.606],
       [ 6073.848],
       [ 5404.064],
       [ 2849.916],
       [ 5367.404],
       [ 6453.67 ],
       [14000.96 ],
       [ 2852.726],
       [ 3057.94 ],
       [ 1598.812],
       [ 2876.59 ],
       [ 4716.492],
       [ 3503.024],
       [ 4204.558],
       [19083.94 ],
       [ 2871.19 ],
       [ 2849.992],
       [ 2368.634],
       [18589.96 ],
       [ 7270.246],
       [ 4977.7  ],
       [ 5822.806],
       [ 7367.41 ],
       [23472.92 ],
       [ 5450.346],
       [20128.02 ],
       [ 6374.782],
       [ 2809.162],
       [ 6862.982],
       [ 4785.418],
       [ 2971.744],
       [ 6800.618],
       [ 2354.33 ],
       [ 6704.48 ],
       [ 4719.902],
       [ 3598.058],
       [ 3477.33 ],
       [ 7722.838],
       [ 2686.472],
       [ 4272.828],
       [ 7977.962],
       [20285.6  ],
       [ 4147.522],
       [20376.6  ],
       [17243.46 ],
       [ 3439.73 ],
       [17467.64 ],
       [ 4803.746],
       [ 3570.116],
       [ 3332.958],
       [20903.3  ],
       [19524.08 ],
       [ 3394.366],
       [ 7908.12 ],
       [ 2084.284],
       [ 3610.212],
       [ 2414.954],
       [ 6665.66 ],
       [ 4107.14 ],
       [ 7079.896],
       [ 3242.886],
       [ 1934.072],
       [ 5833.184],
       [18961.96 ],
       [ 3369.514],
       [ 7950.79 ],
       [15189.38 ],
       [ 3565.848],
       [24595.08 ],
       [ 4429.056],
       [18842.06 ],
       [ 5523.814],
       [ 5302.874],
       [ 2951.31 ],
       [ 5145.944],
       [ 5864.774],
       [ 2907.98 ],
       [ 7325.306],
       [ 2303.238],
       [20207.38 ],
       [ 8493.552],
       [ 2707.384],
       [ 5547.244],
       [ 5869.91 ],
       [ 7790.464],
       [ 3899.922],
       [ 2506.366],
       [ 6082.95 ],
       [17216.22 ],
       [ 3440.644],
       [ 4168.364],
       [17467.64 ],
       [ 3040.826],
       [ 9411.95 ],
       [ 4006.876],
       [14552.18 ],
       [ 5976.264],
       [ 5272.064],
       [ 2248.782],
       [16186.58 ],
       [ 2869.902],
       [21851.42 ],
       [ 2376.752],
       [ 5144.732],
       [ 3921.578],
       [ 1661.338],
       [ 5395.384],
       [ 4447.332],
       [ 2627.29 ],
       [17211.78 ],
       [19374.94 ],
       [ 3553.436],
       [ 6583.814],
       [22247.12 ],
       [ 3901.168],
       [ 1975.18 ],
       [ 3272.3  ],
       [ 2886.464],
       [ 2319.888],
       [ 2188.84 ],
       [21220.4  ],
       [ 6227.884],
       [18232.82 ],
       [21918.42 ],
       [ 6980.694],
       [19712.1  ],
       [ 2467.7  ],
       [30902.34 ],
       [ 5069.214],
       [ 6842.558],
       [16984.74 ],
       [ 3027.212],
       [15558.2  ],
       [ 3327.678],
       [ 5404.83 ],
       [ 7995.626],
       [ 4026.276],
       [ 5142.084],
       [13677.18 ],
       [ 6135.686],
       [15079.18 ],
       [ 7116.162],
       [17019.38 ],
       [ 8171.788],
       [ 2247.208],
       [ 6091.1  ],
       [ 3630.272],
       [ 2694.492],
       [ 5318.596],
       [22592.76 ],
       [ 9399.798],
       [ 6599.212],
       [ 4979.864],
       [ 6395.696],
       [ 2839.266],
       [ 5531.402],
       [ 3543.586],
       [20311.2  ],
       [ 5360.838],
       [ 6304.196],
       [ 5241.174],
       [ 6198.62 ],
       [ 7346.994],
       [12504.18 ],
       [ 5330.368],
       [ 6657.032],
       [ 3501.362],
       [ 7716.476],
       [17977.26 ],
       [ 4815.902],
       [ 2963.756],
       [17981.04 ],
       [ 6185.142],
       [ 4106.438],
       [ 5810.728],
       [ 7096.378],
       [ 5125.768],
       [ 7577.044],
       [ 3301.982],
       [ 3655.742],
       [ 5765.098],
       [ 8610.228],
       [ 3956.232],
       [22001.1  ],
       [ 2207.208],
       [ 2664.796],
       [ 5837.746],
       [ 1306.522],
       [ 4341.846],
       [ 3113.908],
       [ 2636.814],
       [15987.64 ],
       [ 2952.436],
       [ 9877.984],
       [ 4617.96 ],
       [ 3324.86 ],
       [ 8677.92 ],
       [ 4818.038],
       [ 7348.326],
       [10107.688],
       [ 3245.056]])

## Step 7 Passing y-test(actual) and y_pred(model_prediction) to evaluation metrics

#### in this step we are passing our actual target variable and model prediction to evaluation metrics 
- To check how accurate our model is performing

In [181]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7408695812691444

this shows are model is performing 74% accurately

## Saving Production files

In [182]:
import joblib
joblib.dump({'model':model,'cat_encod':OHE,'num_encod':scaler},'MmodelL_prod_files.pkl')

['MmodelL_prod_files.pkl']

In [183]:
prod_files = joblib.load('MmodelL_prod_files.pkl')

In [184]:
prod_files['model']

KNeighborsRegressor()

In [185]:
prod_files['cat_encod']

OneHotEncoder(sparse_output=False)

In [186]:
prod_files['num_encod']

MinMaxScaler()